### ISSUE TITLE
kaggle_apollo_combined_6691_origin.json文件

### ISSUE THREAD

**Issue by enhenghengheng** [stevenwudi/Kaggle_PKU_Baidu#63]
您好，我很仰慕您，从6DVNet开始一直在跟随您的脚步，我最近在复现您kaggle PKU比赛中的结果，但是遇到了问题，我想知道这个文件kaggle_apollo_combined_6691_origin.json
的含义、在哪可以找到或者我自己通过数据集如何构建。

**Comment by stevenwudi** [comment]
Hi, **kaggle_apollo_combined_6691_origin.json** is the annotation file from the combination of ApolloScape and Kaggle (We also cleaned up the noisy images with mesh overlay visualisation).

Alternatively, you can use **train.json** from the Kaggle file.

We have uploaded a json file to google drive as:

https://drive.google.com/open?id=1gEK7aGvTSAi8o2Jq3PgFky_YYX-HpJDt

**Comment by enhenghengheng** [comment]
好的，谢谢您百忙之中的解答，我会再仔细的进行调试。
